title: kappann.eu
author: 
  name: Claudio Nicoli Pannacci
  email: claudio.pannacci@protonmail.com
description: > 
  a website i said i would never make

show_excerpts: false

remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
